apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
    tier: back
  name: worker
spec:
  minReadySeconds: 20
  replicas: 1
  template:
    spec:
      containers:
        - image: baugereau/worker
        name: worker
