apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
    tier: back
  name: worker
  namespace: instavote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
        tier: back
    spec:
      containers:
      - image: baugereau/worker
        name: worker
        resources: {}
