---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1h 
  ref:
    branch: main
  timeout: 1m0s
  secretRef:
    name: github-instavote
  url: https://github.com/baugereau/instavote-deploy.git

