apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels: 
  app: vote
  tier: front
  name: vote
spec:
  replicas: 5
  template:
    spec:
      containers:
      - image: baugereau/vote
        name: vote
        envFrom:
          - configMapRef:
              name: voteoptions
              options: true
